#!/usr/bin/env python3
"""codex_claimkeep_read — READ injection for a Codex-brained agent.

Codex has no SessionStart hook either, but it reads `AGENTS.md` natively at the start of a
run — that is the SessionStart-equivalent. So the default mode renders the HEAD (newest)
ClaimKeep brief and writes it into a MANAGED BLOCK of AGENTS.md, idempotently. `--stdout`
instead prints the brief markdown so the gateway can prepend it directly when it assembles
the prompt.

Rendering reuses the PUBLISHED renderer (`claimkeep postcompact`) for exact parity — we do
not re-implement brief formatting.

Importable:
    from codex_claimkeep_read import head_brief_markdown, update_agents_md
    md = head_brief_markdown("~/.aria/claimkeep/briefs")
    if md:
        update_agents_md("/path/to/AGENTS.md", md)

CLI:
    python3 codex_claimkeep_read.py --brief-dir ~/.aria/claimkeep/briefs --agents /path/AGENTS.md
    python3 codex_claimkeep_read.py --brief-dir ~/.aria/claimkeep/briefs --stdout

Env: CLAIMKEEP_HOME — path to the claimkeep checkout, prepended to PYTHONPATH for the
`-m claimkeep` subprocess when the package is not pip-installed (unused if it is).
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from typing import Dict, List, Optional

BEGIN = "<!-- CLAIMKEEP:BEGIN (auto-generated by codex_claimkeep_read; do not edit inside) -->"
END = "<!-- CLAIMKEEP:END -->"


def _expand(path: str) -> str:
    return os.path.abspath(os.path.expanduser(path))


def _claimkeep_env(brief_dir: str) -> Dict[str, str]:
    env = dict(os.environ)
    env["CLAIMKEEP_BRIEF_DIR"] = _expand(brief_dir)
    home = os.environ.get("CLAIMKEEP_HOME")
    if home:
        home = _expand(home)
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = home + (os.pathsep + existing if existing else "")
    return env


def head_brief_markdown(brief_dir: str) -> str:
    """Render the newest brief in brief_dir to markdown (empty string if none / render fails)."""
    proc = subprocess.run(
        [sys.executable, "-m", "claimkeep", "postcompact", "--event", "SessionStart"],
        capture_output=True,
        text=True,
        env=_claimkeep_env(brief_dir),
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        return ""
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return ""
    return payload.get("hookSpecificOutput", {}).get("additionalContext", "") or ""


def _defuse(markdown: str) -> str:
    """Neutralise block markers appearing inside brief content.

    A brief is verbatim text from a session, and a session that discusses this
    file will quote these markers — the production AGENTS.md carried a claim
    describing the marker bug, which then caused it. Left intact, that string
    closes the managed block from the inside. The comment syntax is stripped so
    the sentence still reads while no longer being a marker.
    """
    return markdown.replace(BEGIN, "[claimkeep:begin]").replace(END, "[claimkeep:end]")


def update_agents_md(agents_path: str, markdown: str) -> str:
    """Insert/replace the ClaimKeep managed block in AGENTS.md. Idempotent; never touches
    content outside the markers. No-op guard: caller should skip empty markdown."""
    agents_path = _expand(agents_path)
    block = f"{BEGIN}\n{_defuse(markdown).rstrip()}\n{END}\n"

    existing = ""
    if os.path.exists(agents_path):
        with open(agents_path, "r", encoding="utf-8") as fh:
            existing = fh.read()

    if BEGIN in existing and END in existing:
        pre = existing.split(BEGIN, 1)[0]
        # The LAST end marker, not the first. A brief that quoted the marker used
        # to close the block early, leaving the rest of the old block in the file
        # and adding a marker on every update — the production AGENTS.md reached
        # one BEGIN and three ENDs. Taking the last one repairs a file already in
        # that state instead of building on it; `_defuse` stops it recurring.
        post = existing.split(END)[-1]
        pre = pre.rstrip("\n")
        joiner = "\n\n" if pre.strip() else ""
        new = pre + joiner + block + post.lstrip("\n")
    else:
        sep = "\n\n" if existing.strip() else ""
        new = existing.rstrip("\n") + sep + block

    parent = os.path.dirname(agents_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(agents_path, "w", encoding="utf-8") as fh:
        fh.write(new)
    return agents_path


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        prog="codex_claimkeep_read",
        description="Render the HEAD ClaimKeep brief into AGENTS.md (or stdout) for Codex.",
    )
    ap.add_argument(
        "--brief-dir", required=True, help="directory holding harvested briefs"
    )
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--agents", help="AGENTS.md path to update (managed block)")
    group.add_argument(
        "--stdout", action="store_true", help="print brief markdown to stdout"
    )
    args = ap.parse_args(argv)

    md = head_brief_markdown(args.brief_dir)
    if not md.strip():
        # No brief yet — do not wipe AGENTS.md, do not print noise.
        sys.stderr.write(
            "codex_claimkeep_read: no brief found in %s (nothing injected)\n"
            % _expand(args.brief_dir)
        )
        return 0

    if args.stdout:
        sys.stdout.write(md.rstrip() + "\n")
    else:
        path = update_agents_md(args.agents, md)
        sys.stderr.write("codex_claimkeep_read: updated managed block in %s\n" % path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
